source "https://rubygems.org"

gem "rails", "~> 6.0.2", ">= 6.0.2.2"
gem "bootsnap", ">= 1.4.2", require: false
gem "devise", "~> 4.7"
gem "pg", ">= 0.18", "< 2.0"
gem "puma", "~> 4.1"
gem "turbolinks", "~> 5"
gem "webpacker", "~> 4.0"
