version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: twilio-ruby
    versions:
    - 5.46.1
    - 5.47.0
    - 5.48.0
    - 5.49.0
    - 5.50.0
    - 5.51.0
  - dependency-name: google-protobuf
    versions:
    - 3.14.0
    - 3.15.0
    - 3.15.0.rc.1
    - 3.15.0.rc.2
    - 3.15.1
    - 3.15.2
    - 3.15.3
    - 3.15.4
    - 3.15.5
    - 3.15.6
    - 3.15.7
  - dependency-name: rspec-rails
    versions:
    - 4.0.2
    - 4.1.0
    - 5.0.0
  - dependency-name: rails
    versions:
    - 6.0.3.4
    - 6.0.3.5
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: ruby
    versions:
    - 3.0.0.pre.alpine
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: apexcharts
    versions:
    - 3.23.1
  - dependency-name: "@rails/webpacker"
    versions:
    - 5.2.1
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
