FROM ruby:2.7.1-alpine

# Add basic packages
RUN apk add --update --no-cache \
      build-base \
      postgresql-dev \
      git \
      nodejs \
      yarn \
      tzdata \
      file

WORKDIR /app

# Install gems (for production only)
COPY Gemfile* .ruby-version /app/
RUN bundle config frozen true && \
    bundle config force_ruby_platform true && \
    bundle config build.sassc --disable-march-tune-native && \
    bundle config build.google-protobuf --with-cflags=-D__va_copy=va_copy && \
    bundle config without 'development test' && \
    bundle install -j4 --retry 3

# Verify that protobufs installed? ugh
RUN ruby -e "require 'grpc'; require 'google/protobuf/any_pb'"

# Install Node modules
COPY package.json yarn.lock /app/
RUN yarn install --frozen-lockfile

#### ONBUILD: Add triggers to the image, executed later while building a child image

# Update gems if needed
ONBUILD COPY Gemfile* .ruby-version /app/
ONBUILD RUN bundle install -j4 --retry 3 && \
            # Remove unneeded gems
            bundle clean --force && \
            # Remove unneeded files from installed gems (cached *.gem, *.o, *.c)
            rm -rf /usr/local/bundle/cache/*.gem && \
            find /usr/local/bundle/gems/ -name "*.c" -delete && \
            find /usr/local/bundle/gems/ -name "*.o" -delete

# Update Node modules if needed
ONBUILD COPY package.json yarn.lock /app/
ONBUILD RUN yarn install --frozen-lockfile

# Copy the whole application folder into the image
ONBUILD COPY . /app

ONBUILD RUN RAILS_ENV=production \
            SECRET_KEY_BASE=melonmelonmelonmelonmelonmelonmelon \
            ASSET_COMPILATION=true \
            bundle exec rails assets:precompile

# Remove folders not needed in resulting image
ONBUILD RUN rm -rf node_modules tmp/cache vendor/bundle test spec
