 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/surveys", type: :request do
  # Survey. As you add validations to Survey, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /show" do
    it "renders a successful response" do
      survey = Survey.create! valid_attributes
      get survey_url(survey)
      expect(response).to be_successful
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested survey" do
        survey = Survey.create! valid_attributes
        patch survey_url(survey), params: { response: new_attributes }
        response.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the survey" do
        survey = Survey.create! valid_attributes
        patch survey_url(survey), params: { response: new_attributes }
        response.reload
        expect(response).to redirect_to(survey_url(response))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        survey = Survey.create! valid_attributes
        patch survey_url(survey), params: { response: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

end
