 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/survey_invitations", type: :request do
  # SurveyInvitation. As you add validations to SurveyInvitation, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      SurveyInvitation.create! valid_attributes
      get survey_invitations_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      survey_invitation = SurveyInvitation.create! valid_attributes
      get survey_invitation_url(survey_invitation)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_survey_invitation_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      survey_invitation = SurveyInvitation.create! valid_attributes
      get edit_survey_invitation_url(survey_invitation)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new SurveyInvitation" do
        expect {
          post survey_invitations_url, params: { survey_invitation: valid_attributes }
        }.to change(SurveyInvitation, :count).by(1)
      end

      it "redirects to the created survey_invitation" do
        post survey_invitations_url, params: { survey_invitation: valid_attributes }
        expect(response).to redirect_to(survey_invitation_url(SurveyInvitation.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new SurveyInvitation" do
        expect {
          post survey_invitations_url, params: { survey_invitation: invalid_attributes }
        }.to change(SurveyInvitation, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post survey_invitations_url, params: { survey_invitation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested survey_invitation" do
        survey_invitation = SurveyInvitation.create! valid_attributes
        patch survey_invitation_url(survey_invitation), params: { survey_invitation: new_attributes }
        survey_invitation.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the survey_invitation" do
        survey_invitation = SurveyInvitation.create! valid_attributes
        patch survey_invitation_url(survey_invitation), params: { survey_invitation: new_attributes }
        survey_invitation.reload
        expect(response).to redirect_to(survey_invitation_url(survey_invitation))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        survey_invitation = SurveyInvitation.create! valid_attributes
        patch survey_invitation_url(survey_invitation), params: { survey_invitation: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested survey_invitation" do
      survey_invitation = SurveyInvitation.create! valid_attributes
      expect {
        delete survey_invitation_url(survey_invitation)
      }.to change(SurveyInvitation, :count).by(-1)
    end

    it "redirects to the survey_invitations list" do
      survey_invitation = SurveyInvitation.create! valid_attributes
      delete survey_invitation_url(survey_invitation)
      expect(response).to redirect_to(survey_invitations_url)
    end
  end
end
