 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/agency/surveys", type: :request do
  # Agency::Survey. As you add validations to Agency::Survey, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Agency::Survey.create! valid_attributes
      get agency_surveys_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      survey = Agency::Survey.create! valid_attributes
      get agency_survey_url(agency_survey)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_agency_survey_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      survey = Agency::Survey.create! valid_attributes
      get edit_agency_survey_url(agency_survey)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Agency::Survey" do
        expect {
          post agency_surveys_url, params: { agency_survey: valid_attributes }
        }.to change(Agency::Survey, :count).by(1)
      end

      it "redirects to the created agency_survey" do
        post agency_surveys_url, params: { agency_survey: valid_attributes }
        expect(response).to redirect_to(agency_survey_url(@agency_survey))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Agency::Survey" do
        expect {
          post agency_surveys_url, params: { agency_survey: invalid_attributes }
        }.to change(Agency::Survey, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post agency_surveys_url, params: { agency_survey: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested agency_survey" do
        survey = Agency::Survey.create! valid_attributes
        patch agency_survey_url(agency_survey), params: { agency_survey: new_attributes }
        survey.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the agency_survey" do
        survey = Agency::Survey.create! valid_attributes
        patch agency_survey_url(agency_survey), params: { agency_survey: new_attributes }
        survey.reload
        expect(response).to redirect_to(agency_survey_url(survey))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        survey = Agency::Survey.create! valid_attributes
        patch agency_survey_url(agency_survey), params: { agency_survey: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested agency_survey" do
      survey = Agency::Survey.create! valid_attributes
      expect {
        delete agency_survey_url(agency_survey)
      }.to change(Agency::Survey, :count).by(-1)
    end

    it "redirects to the agency_surveys list" do
      survey = Agency::Survey.create! valid_attributes
      delete agency_survey_url(agency_survey)
      expect(response).to redirect_to(agency_surveys_url)
    end
  end
end
